name: Push Changes to Github Pages

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Push Changes to Github Pages
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'src/'
        destination_repo: 'lewisf2001uk/lewisf2001uk.github.io'
        destination_folder: '2024'
        user_email: 'lewisf2001uk@googlemail.com'
        user_name: 'lewisf2001uk'
